apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-backend
  labels:
    app: pokedex
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex
      tier: backend
  template:
    metadata:
      labels:
        app: pokedex
        tier: backend
    spec:
      containers:
      - name: backend
        image: diegorlopez/pokedex-backend:1.7.1-fd-fix 
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "pokedex-redis"
        - name: POSTGRES_HOST
          value: "pokedex-postgres"
        - name: POSTGRES_DB
          value: "pokedex_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pokedex-secrets
              key: postgres-password
        - name: ALLOWED_ORIGINS
          value: "http://pokedex-frontend,http://localhost:3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add: ["SYS_RESOURCE"]
        command: ["sh", "-c", "ulimit -n 65535 && uvicorn app:app --host 0.0.0.0 --port 8000"]
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-backend
  labels:
    app: pokedex
    tier: backend
spec:
  selector:
    app: pokedex
    tier: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP