version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: pokedex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:13-alpine
    container_name: pokedex-postgres
    environment:
      POSTGRES_DB: pokedex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: