apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-postgres
  labels:
    app: pokedex
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex
      tier: database
  template:
    metadata:
      labels:
        app: pokedex
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "pokedex_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pokedex-secrets
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init-db.sql
          subPath: init-db.sql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init-db.sql: |
    -- Script de inicialización de la base de datos para Pokédex
    CREATE TABLE IF NOT EXISTS search_history (
        id SERIAL PRIMARY KEY,
        pokemon_name VARCHAR(100) NOT NULL,
        searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE INDEX IF NOT EXISTS idx_searched_at ON search_history(searched_at);
    
    -- Opcional: Insertar algunos datos de ejemplo
    -- INSERT INTO search_history (pokemon_name, searched_at) VALUES
    -- ('pikachu', NOW() - INTERVAL '1 hour'),
    -- ('charizard', NOW() - INTERVAL '2 hours'),
    -- ('bulbasaur', NOW() - INTERVAL '3 hours');
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-postgres
  labels:
    app: pokedex
    tier: database
spec:
  selector:
    app: pokedex
    tier: database
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi