apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init-db.sql: |
    -- Copia exacta de tu init-db.sql
    CREATE TABLE IF NOT EXISTS pokemon (
        id INTEGER PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        height INTEGER,
        weight INTEGER,
        sprite TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS pokemon_types (
        id SERIAL PRIMARY KEY,
        pokemon_id INTEGER REFERENCES pokemon(id),
        type_name VARCHAR(20) NOT NULL,
        UNIQUE(pokemon_id, type_name)
    );

    CREATE TABLE IF NOT EXISTS search_history (
        id SERIAL PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
