version: "3.9"

services:
  registry:
    build: .
    container_name: kind-registry
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - registry-data:/var/lib/registry

volumes:
  registry-data:
    driver: local
