apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
- 01-namespace.yaml
- 02-pvc.yaml
- 03-deployment.yaml
- 04-service.yaml
- ../components/rbac  # ✅ Importa RBAC de components