apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-frontend
  labels:
    app: pokedex
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex
      tier: frontend
  template:
    metadata:
      labels:
        app: pokedex
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: diegorlopez/pokedex-frontend:nginx  # ← Cambiado a imagen nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80  # ← Cambiado de 5500 a 80 (Nginx)
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health  # ← Cambiado a endpoint de health de Nginx
            port: 80       # ← Cambiado a puerto 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health  # ← Health check de Nginx
            port: 80       # ← Puerto 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-frontend
  labels:
    app: pokedex
    tier: frontend
spec:
  selector:
    app: pokedex
    tier: frontend
  ports:
  - port: 80
    targetPort: 80  # ← Cambiado de 5500 a 80 (Nginx)
  type: LoadBalancer