services:
  jenkins:
    container_name: jenkins_server
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home   # volumen antiguo
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    user: root
    
volumes:
  jenkins_home:   # referencia al volumen existente

