# kind-config-simple.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pokedex-cluster
nodes:
- role: control-plane
- role: worker
- role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
    endpoint = ["http://kind-registry:5000"]